"""update on delete foreign key

Revision ID: 32c79cec2fca
Revises: 34c7f4ce7d7a
Create Date: 2026-07-17 16:21:33.166993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c79cec2fca'
down_revision: Union[str, Sequence[str], None] = '34c7f4ce7d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_trails_user_id_fkey'), 'audit_trails', type_='foreignkey')
    op.create_foreign_key(None, 'audit_trails', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('otp_verifications_user_id_fkey'), 'otp_verifications', type_='foreignkey')
    op.create_foreign_key(None, 'otp_verifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'otp_verifications', type_='foreignkey')
    op.create_foreign_key(op.f('otp_verifications_user_id_fkey'), 'otp_verifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'audit_trails', type_='foreignkey')
    op.create_foreign_key(op.f('audit_trails_user_id_fkey'), 'audit_trails', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
